### PR TITLE
Create Model Management UI

### LINKED ISSUE #29: [Web] UI for model version management
This should roughly correspond to the [create / archive / edit / list]ModelVersions GQL methods

@StephenODea54 - I'll leave this to you to fill out any additonal info

### PR DESCRIPTION
**Pull request by StephenODea54**
Closes #29 

Added wireframe for Model Management UI. When we actually start getting this data from a server, we'll come back and add in features such as inputs, filtering, pagination, better responsive designs, etc.

Also altered the padding and responsive design for the dashboard layout so that the elements align better with the contents of the children.

Also also, added a status icon component for the table which helps the user visually represent their model health quickly (green - success, red - failure, etc.)

image

### CODE REVIEW

**Comment by wetherc** [comment]
Completely random sample models I see 😂

**Review by wetherc — APPROVED** [review]
Looks great to me. When we get to making the gql calls, thoughts on not displaying archived counts on the main page? Only mention because it's a hard coded example, but not sure there's value showing that more generally (i.e., when not looking at the list of versions for a specific model)

**Comment by StephenODea54** [comment]
> Looks great to me. When we get to making the gql calls, thoughts on not displaying archived counts on the main page? Only mention because it's a hard coded example, but not sure there's value showing that more generally (i.e., when not looking at the list of versions for a specific model)

Cool with me!

**Comment by StephenODea54** [comment]
> Completely random sample models I see 😂

 Completely random 😂

**Pull request merged**
